alias: Zatahnout zaluzie pri teple venku odpoledne
description: ''
trigger:
  - platform: time
    at: '12:00:00'
  - platform: numeric_state
    entity_id: sensor.prumerna_venkovni_teplota
    above: '17'
condition:
  - condition: and
    conditions:
      - condition: sun
        before: sunset
        before_offset: '00:30:00'
      - condition: numeric_state
        entity_id: sensor.netatmo_selfiehome_loznice_vitr_wind_strength
        below: '35'
      - condition: numeric_state
        entity_id: sensor.prumerna_venkovni_teplota
        above: '17'
      - condition: time
        after: '11:59:00'
      - condition: device
        device_id: aaaaa
        domain: alarm_control_panel
        entity_id: alarm_control_panel.jablotron_sekce_vse
        type: is_disarmed
action:
  - scene: scene.odpoledne_2
mode: single
